import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import PageLoading from "@/components/layouts/loading/PageLoading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=chillax@600,500,300,700,400&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="./assets/icon.png" sizes="any" />

        <title>Gradients CSS</title>
      </head>

      <body className={inter.className}>
        <PageLoading />

        {children}

        <Toaster />
      </body>
    </html>
  );
}
